### ISSUE TITLE
[CI] Disallow GitHub CI/CD pipelines for draft PRs.

### ISSUE THREAD

**Issue by lancorer** [dp-labs/dora#116]
Could alter GitHub workflow pipeline like:

```yaml
on:
  // ...
  pull_request:
    branches: ["**"]
    types: [synchronize, opened, reopened, ready_for_review]
// ...
jobs:
  // ...
  if: github.event.pull_request.draft == false
  // ...
```
